# Generated by Django 5.2.8 on 2025-11-22 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reeducando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('alcunha', models.CharField(blank=True, max_length=50, null=True, verbose_name='Alcunha/Apelido')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG')),
                ('nome_pai', models.CharField(max_length=255, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(max_length=255, verbose_name='Nome da Mãe')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=100)),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO_ESTAVEL', 'União Estável')], max_length=20)),
                ('pena_aplicada', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pena Aplicada')),
                ('regime_inicial', models.IntegerField(choices=[(1, 'Fechado'), (2, 'Semi-aberto'), (3, 'Aberto'), (4, 'Provisório')], verbose_name='Regime Inicial')),
                ('data_prisao', models.DateField(verbose_name='Data de Prisão')),
                ('data_prevista_termino', models.DateField(verbose_name='Data Prevista de Término')),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo'), (3, 'Transferido'), (4, 'Egresso')], default=1)),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('observacoes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Observações')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('area_atuacao', models.CharField(max_length=100, verbose_name='Área de Atuação')),
                ('formacao_academica', models.CharField(max_length=100, verbose_name='Formação Acadêmica')),
                ('disciplinas_ministradas', models.TextField(blank=True, help_text='Listar disciplinas separadas por vírgula', null=True)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo'), (3, 'Afastado')], default=1)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, max_length=500, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=255, verbose_name='Nome do Curso/Disciplina')),
                ('descricao_ementa', models.TextField(verbose_name='Descrição/Ementa')),
                ('carga_horaria', models.CharField(max_length=50, verbose_name='Carga Horária Total')),
                ('modalidade', models.CharField(blank=True, max_length=50, null=True)),
                ('modulos_aulas', models.TextField(blank=True, null=True, verbose_name='Conteúdo/Módulos')),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Em Desenvolvimento'), ('3', 'Inativo')], default='1', max_length=1)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('professor_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='educamais_app.professor', verbose_name='Professor Responsável')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
