# Generated by Django 5.2.8 on 2025-11-23 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educamais_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('status', models.IntegerField(choices=[(1, 'Em Andamento'), (2, 'Concluído'), (3, 'Trancado'), (4, 'Evadido')], default=1, verbose_name='Status da Matrícula')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educamais_app.reeducando', verbose_name='Aluno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educamais_app.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'unique_together': {('aluno', 'curso')},
            },
        ),
    ]
