# Generated by Django 5.2.8 on 2025-11-23 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educamais_app', '0002_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_aula', models.CharField(max_length=100, verbose_name='Módulo/Aula Concluída')),
                ('nota_avaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Nota Obtida')),
                ('data_conclusao', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora Conclusão')),
                ('tempo_gasto', models.DurationField(blank=True, null=True, verbose_name='Tempo de Estudo')),
                ('status_sincronizacao', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Sincronizado')], default=2)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educamais_app.matricula', verbose_name='Matrícula do Aluno')),
            ],
            options={
                'verbose_name': 'Progresso / Nota',
                'verbose_name_plural': 'Progresso Acadêmico',
            },
        ),
    ]
