# Generated by Django 5.2.8 on 2025-11-23 19:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educamais_app', '0003_progresso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_validacao', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Código de Validação')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('arquivo_pdf', models.CharField(blank=True, max_length=255, null=True, verbose_name='Caminho do Arquivo')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educamais_app.matricula', verbose_name='Matrícula')),
            ],
            options={
                'verbose_name': 'Certificado Emitido',
                'verbose_name_plural': 'Certificados Emitidos',
            },
        ),
    ]
