# Generated by Django 5.2.8 on 2025-11-23 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educamais_app', '0004_certificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('perfil_acesso', models.IntegerField(choices=[(1, 'Administrador Geral'), (2, 'Gestor'), (3, 'Operador')], verbose_name='Perfil de Acesso')),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo'), (3, 'Suspenso')], default=1)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Administrador/Operador',
                'verbose_name_plural': 'Administradores e Operadores',
            },
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('unidade_responsavel', models.IntegerField(verbose_name='ID da Unidade Responsável')),
                ('cargo_funcao', models.CharField(max_length=100, verbose_name='Cargo/Função')),
                ('nivel_acesso', models.IntegerField(choices=[(1, 'Gestor Geral'), (2, 'Coordenador de Unidade'), (3, 'Supervisor Pedagógico')], verbose_name='Nível de Acesso')),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo'), (3, 'Afastado')], default=1)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Gestor',
                'verbose_name_plural': 'Gestores',
            },
        ),
    ]
