# Generated by Django 5.2.8 on 2025-11-23 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educamais_app', '0005_administrador_gestor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(max_length=200, verbose_name='Título Principal (Hero)')),
                ('descricao_hero', models.TextField(verbose_name='Descrição (Hero)')),
                ('texto_botao', models.CharField(max_length=50, verbose_name='Texto do Botão')),
                ('link_botao', models.CharField(max_length=200, verbose_name='Link do Botão')),
                ('data_ultima_modificacao', models.DateTimeField(auto_now=True)),
                ('autor_modificacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor da Modificação')),
            ],
            options={
                'verbose_name': 'Conteúdo Home',
                'verbose_name_plural': 'Conteúdo Home',
            },
        ),
    ]
